# Typus Roles Configuration File
#
# Use the README file as a reference to customize settings.

admin:
  Article: create, read, update, delete
  Category: create, read, update, delete
  Comment: create, read, update, delete
  Profile: create, read, update, delete
  User: create, read, update, delete
